echo "the varibales that are passed from are $@"
echo "No of variables passed are $#"
echo "the script that is being executed is $0"
echo "Current dorectory : $PWD"
echo "home directory of current user: $HOME"
echo "PID of the current commnd : $$"